config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index' , as: 'home'
  resources :users, only: [:new, :create]
  resources :posts , only: [:new, :create]
  
  get '/signup' => 'users#new'  , as: 'signup'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#login' , as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#logout' , as: 'logout'



  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates(:title,presence: true,length: { maximum: 50 })
    validates(:bodyText,presence: true,length: { maximum: 200 })
    validates(:user_id, presence: true)
end

app/models/user.rb
class User < ApplicationRecord
    before_save{self.email = self.email.downcase}
    has_many :posts

    validates(:username,presence: true, uniqueness: true)

    valid_email = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates(:email,presence: true, uniqueness: {case_sensitive: false},
        format: {with: valid_email})

    has_secure_password()
    

    def generate_token
        random_token = SecureRandom.urlsafe_base64()
        hashed_token = hash_token(random_token)
        self.update_attribute(:remember_token,hashed_token)
    end

    def forget_token
        self.update_attribute(:remember_token,nil)
    end

    def authenticate_token(token)
        return self.remember_token == token
    end

    private def hash_token(token)
        Digest::SHA256.base64digest(token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    def logged
        unless is_logged?
            flash['danger'] = 'please log in'
            redirect_to login_path
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :logged , only: [:new,:create]

    def index
        @posts = Post.all.order("created_at DESC").paginate(page: params['page'],per_page: 4)
    end

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.new(post_params)

        if @post.save
            flash[:success] = 'Post created!'
            redirect_to home_path
        else
            render 'new'
        end
    end

    private def post_params
        params.require('post').permit(:title,:bodyText)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login
        
    end

    def create
        password = params['session']['password']
        user = User.find_by(email: params['session']['email'])

        if user 
            if user.authenticate(password)
                #remember login session option
                params['session']['remember_me'] == '1' ? remember_session(user) : forget_session(user)

                log_in(user)
              
                flash['success'] = 'Successfully Logged In!'
                redirect_to home_path
            else
                flash.now['danger'] = 'invalid email/password'
                render 'login'
            end
        else
            flash.now['danger'] = 'user not registered'
            render 'login'
        end

    end

    def logout
        forget_session(current_user)
        session['user_id'] = nil
        flash['success'] = 'Successfully Logged Out!'
        redirect_to home_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save()
            flash[:success] = 'you are now registered!'
            redirect_to home_path
        else
            render 'new'
        end 
    end


    private

    def user_params
        params.require('user').permit(:username,:email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session['user_id'] = user.id
    end

    def current_user
        @user = @user || User.find_by(id: session[:user_id]) if is_logged?
    end

    def remember_session(user)
        user.generate_token
        cookies.permanent['remember_token'] = user.remember_token
        cookies.permanent.signed['user_id'] = user.id
    end

    def forget_session(user)
        cookies.delete('remember_token')
        cookies.delete('user_id')
        user.forget_token()
    end


    def is_logged?
        #if there's no session , then check cookies
        if session['user_id'].nil?

            if cookies.signed['user_id']
                user = User.find_by(id: cookies.signed['user_id'])
                if user && user.authenticate_token(cookies['remember_token'])
                    log_in(user)
                end      
            end
        #session exists
        else
            return true
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= render 'partials/flash_messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/partials/_flash_messages.html.erb
<% flash.each do |type,message|%>
    <div class="alert alert-<%= type %>">
        <%= message %>
    </div>
<% end %>

app/views/partials/_navbar.html.erb
<% if is_logged? %>
    <div id='welcome-user'>  
        <div class='container-fluid'>
            Connected as: <span><%= current_user.username %></span> 
        </div>
    </div>
<% end %>

<div class='navbar navbar-expand-md navbar-dark bg-dark'>

    <%= link_to 'OnlyMembers', home_path , class: 'navbar-brand' %>

     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-toggler">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id='navbar-toggler'>

        <ul class='navbar-nav'>
            <li class='<%= 'active' if current_page?(home_path) %>'><%= link_to 'Posts', home_path , class: 'nav-link' %></li>
        </ul>

        <ul class='navbar-nav ml-auto'>
            <% if is_logged? %>
                <li class='<%= 'active' if current_page?(new_post_path) %>'><%= link_to 'New post', new_post_path , class: 'nav-link' %></li>
                 <li><%= link_to 'Logout', logout_path, class: 'nav-link' %></li>
            <% else %>
                <li class='<%= 'active' if current_page?(signup_path) %>'><%= link_to 'Signup', signup_path , class: 'nav-link' %></li>
                <li class='<%= 'active' if current_page?(login_path) %>'><%= link_to 'login', login_path , class: 'nav-link' %></li>
            <% end %>

        </ul>

    </div>

</div>

app/views/posts/_error_messages.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-danger">
        <ul class='errors-list'>
            <% @post.errors.full_messages.each do |message|%>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class='card post shadow'>
    <h3 class='card-header'><%= post.title %> </h3>
    <div class='card-body'>
        <% if is_logged? %>
            <p>By: <span class='text-primary'><%= post.user.username %></span></p>
        <% end %>
        <p><%= post.bodyText %></p>
    </div>
    <span class='card-footer'>Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
</div>

app/views/posts/index.html.erb
<div class='container'>
    <h1 class='text-center'>Posts: </h1>
    <%= render @posts %>
    <%= will_paginate(@post,:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    
    
</div>

app/views/posts/new.html.erb
<%= form_for(@post,html: {class: 'container'}) do |f| %>

    <h1>Make a new post</h1>

    <%= render 'posts/error_messages' %>

    <div class='form-group'>
        <%= f.label :title %>
        <%= f.text_field :title , class: 'form-control' , placeholder: 'title' %>
    </div>

    <div class='form-group'>
        <%= f.text_area :bodyText , class: 'form-control' , placeholder: 'Write Body Text here' %>
    </div>
    
    <%= f.submit "Post", class: "btn btn-primary" %>

<% end %>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger">
        <ul class='errors-list'>
            <% @user.errors.full_messages.each do |message|%>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user, url: '/signup',html: {class: 'container'}) do |f| %>

    <h1>Create a new user</h1>

    <%= render 'users/error_messages' %>

    <div class='form-group'>
        <%= f.label :username %>
        <%= f.text_field :username , class: 'form-control' , placeholder: 'username' %>
    </div>
  
    <div class='form-group'>
        <%= f.label :email %>
        <%= f.email_field :email , class: 'form-control' , placeholder: 'email'%>
    </div>

    <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password , class: 'form-control' , placeholder: 'password'%>
    </div>

    <div class='form-group'>
        <%= f.label :password_confirmation, "Confirm password" %>
        <%= f.password_field :password_confirmation , class: 'form-control' , placeholder: 'confirm password'%>
    </div>

    <%= f.submit "Create account", class: "btn btn-primary" %>

<% end %>